### ISSUE TITLE
`_frontPadding`和`_backPadding`的用处是什么？

### ISSUE THREAD

**Issue by yangboye** [YukangLiu/RateLimiter#1]
您好，我想请问一下`sequence.h`下的`_frontPadding`和`_backPadding`两个私有变量的用处是什么呢？

**Comment by YukangLiu** [comment]
保证Sequence对象中真正会被访问的_seq不会与其它对象在同一个缓存行中，避免了伪共享的发生




------------------ 原始邮件 ------------------
发件人: Yangbo Ye ***@***.***&gt;
发送时间: 2021年8月24日 19:10
收件人: YukangLiu/RateLimiter ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[YukangLiu/RateLimiter] `_frontPadding`和`_backPadding`的用处是什么？ (#1)





 
您好，我想请问一下sequence.h下的_frontPadding和_backPadding两个私有变量的用处是什么呢？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
